### PR TITLE
fix: convert custom errors to use failure

### PR DESCRIPTION
**Pull request by zcstarr**
@mersinvald wasn't sure if this was the conversion thought you had in mind. I haven't done the whole thing or killed comments.  But is this the intent ?

### CODE REVIEW

**Comment by mersinvald** [comment]
@zcstarr LGTM, I will merge it as soon as I fix the releases

**Review by mersinvald — APPROVED** [review]

**Comment by zcstarr** [comment]
> @zcstarr LGTM, I will merge it as soon as I fix the releases

I think this still needs a little more work, it's got commented out code and stuff. I'll ping you with a PTAL when I remove that stuff and add this change to the rest of the code base for error handling.

**Comment by zcstarr** [comment]
@mersinvald  PTAL . I did the rest of the refactor and added a comment on some lines I removed mind weighing in one more time?

**Comment by mersinvald** [comment]
@zcstarr can you please rebase the branch onto the current master, so CI would fire for this PR?

**Comment by zcstarr** [comment]
@mersinvald it is rebased 🤔 . I can always force push again ....

**Comment by mersinvald** [comment]
@zcstarr it's rebased onto your fork master, not the current master of this repo

**Comment by zcstarr** [comment]
I did some linting as well

**Comment by zcstarr** [comment]
closing for CI reasons

**Pull request closed without merging**
